#!/usr/bin/env bash
# A script that displays "Best School" 10 times, printing "Hi" on the 9th line
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
