#!/usr/bin/env bash
# This script displays different numbers and messages based on the loop iteration
i=1
while [ $i -le 20 ]
do
	case $counter in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	((i++))
done
